global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kaven-monitor'

scrape_configs:
  - job_name: 'kaven-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
